[config]
# ...

[templates.example]
input_path = '~/.config/matugen/templates/example.conf'
output_path = '~/.config/matugen/output/example.conf'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/matugen/output/hyprland-colors.conf'
post_hook = 'hyprctl reload'

[templates.hyprtoolkit]
input_path = '~/.config/matugen/templates/hyprtoolkit.conf'
output_path = '~/.config/hypr/hyprtoolkit.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/styles/matugen.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.mako]
input_path = '~/.config/mako/config-env'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/matugen.ini'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/matugen.conf'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.helix]
input_path = '~/.config/matugen/templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/matugen/color.ini'
post_hook = 'spicetify apply -n'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/matugen/scripts/steam/Adwaita-for-Steam/adwaita/colorthemes/matugen/matugen.css'

[templates.signal]
input_path = '~/.config/matugen/templates/signal.css'
output_path = '~/.config/matugen/output/signal-colors.css'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/GTK-colors/gtk-3.0/gtk.css'
output_path = '~/.themes/Matugen/gtk-3.0/gtk.css'
[templates.gtk3-dark]
input_path = '~/.config/matugen/templates/GTK-colors/gtk-3.0/gtk-dark.css'
output_path = '~/.themes/Matugen/gtk-3.0/gtk-dark.css'
[templates.gtk4]
input_path = '~/.config/matugen/templates/GTK-colors/gtk-4.0/gtk.css'
output_path = '~/.themes/Matugen/gtk-4.0/gtk.css'
[templates.gtk4-dark]
input_path = '~/.config/matugen/templates/GTK-colors/gtk-4.0/gtk-dark.css'
output_path = '~/.themes/Matugen/gtk-4.0/gtk-dark.css'
[templates.gtk-cinnamon]
input_path = '~/.config/matugen/templates/GTK-colors/cinnamon/cinnamon.css'
output_path = '~/.themes/Matugen/cinnamon/cinnamon.css'
[templates.gtk-gnome]
input_path = '~/.config/matugen/templates/GTK-colors/gnome-shell/gnome-shell.css'
output_path = '~/.themes/Matugen/gnome-shell/pad-osd.css'

# [templates.quickshell]
# input_path = "~/.config/matugen/templates/quickshell.qml"
# output_path = "/home/sisa/Code/Tests/quickshell/Colors.qml"
