# : Manager [[[

[mgr]
cwd = { fg = "#e9e0e7" }

# Tab
tab_active = { fg = "#422255", bg = "#e0b8f5", bold = true }
tab_inactive = { fg = "#f4d9ff", bg = "#2b0b3f" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7474", bg = "#ff7474" }
marker_cut = { fg = "#ffdada", bg = "#ffdada" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f4b7b8", bg = "#f4b7b8" }

# Count
count_copied = { fg = "#331113", bg = "#ffdada" }
count_cut = { fg = "#331113", bg = "#ffdada" }
count_selected = { fg = "#422255", bg = "#f4b7b8" }

# Border
border_symbol = " "
border_style  = { fg = "#e0b8f5" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#422255", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e0b8f5", fg = "#422255", bold = true }
normal_alt  = { bg = "#4b454d", fg = "#cec3ce" }

# Select mode
select_main = { bg = "#d3c0d8", fg = "#382c3e", bold = true }
select_alt  = { bg = "#4b454d", fg = "#cec3ce" }

# Unset mode
unset_main = { bg = "#f4b7b8", fg = "#4c2527", bold = true }
unset_alt  = { bg = "#4b454d", fg = "#cec3ce" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e0b8f5", bg = "#3c383d" }
progress_error = { fg = "#ffb4ab", bg = "#3c383d" }

# Permissions
permissions_t = { fg = "#91629e" }
permissions_w = { fg = "#e03235" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4141" }
permissions_s = { fg = "#c840ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e0b8f5" }
active = { fg = "#f4b7b8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#e0b8f5" }
value = { fg = "#e9e0e7" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#e0b8f5", bold = true, bg = "#161217" }
inactive = { fg = "#d3c0d8", bg = "#161217" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e0b8f5", bg = "#422255" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e0b8f5" }
title = {}
hovered = { fg = "#ffdada", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c383d" }
cand = { fg = "#e0b8f5" }
rest = { fg = "#422255" }
desc = { fg = "#e9e0e7" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e9e0e7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e9e0e7" }
run = { fg = "#e9e0e7" }
footer = { fg = "#382c3e", bg = "#d3c0d8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f4b7b8" }
title_warn = { fg = "#e0b8f5" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e9e0e7" },
    { name = "*/", fg = "#e0b8f5" },
]

# : ]]]
